// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkFLlOuDOi7_qYyAmNlS-YCT3TXA-p_io',
    appId: '1:145549009607:web:5eda033420317fe60f54e2',
    messagingSenderId: '145549009607',
    projectId: 'recycle-app-ded0b',
    authDomain: 'recycle-app-ded0b.firebaseapp.com',
    storageBucket: 'recycle-app-ded0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA58-xJhBoiWIXsr_ZYVA4KAFqBpXJ0X4',
    appId: '1:145549009607:android:4a6e3697df8ad8e80f54e2',
    messagingSenderId: '145549009607',
    projectId: 'recycle-app-ded0b',
    storageBucket: 'recycle-app-ded0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bvGpKUKsVN6rUrtsrCx2ndBXFtqmIvk',
    appId: '1:145549009607:ios:eb841a4b882b9b7b0f54e2',
    messagingSenderId: '145549009607',
    projectId: 'recycle-app-ded0b',
    storageBucket: 'recycle-app-ded0b.firebasestorage.app',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8bvGpKUKsVN6rUrtsrCx2ndBXFtqmIvk',
    appId: '1:145549009607:ios:eb841a4b882b9b7b0f54e2',
    messagingSenderId: '145549009607',
    projectId: 'recycle-app-ded0b',
    storageBucket: 'recycle-app-ded0b.firebasestorage.app',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkFLlOuDOi7_qYyAmNlS-YCT3TXA-p_io',
    appId: '1:145549009607:web:121be257c01026a00f54e2',
    messagingSenderId: '145549009607',
    projectId: 'recycle-app-ded0b',
    authDomain: 'recycle-app-ded0b.firebaseapp.com',
    storageBucket: 'recycle-app-ded0b.firebasestorage.app',
  );
}
